language: node_js
node_js:
  - "10"

cache:
  yarn: true

branches:
  only:
    - master

jobs:
  fail_fast: true

  include:
    # runs linting and tests with current locked deps
    - name: "Locked Dependencies: Node 6"
      node_js: "6"

    - name: "Locked Dependencies: Node 8"
      node_js: "8"

    - name: "Locked Dependencies: Node 10"

    - name: "Floating Dependencies: Node 10"
      install:
        - yarn install --no-lockfile --non-interactive
